// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BData.Models
{
    public partial class Adresse
    {
        public Adresse()
        {
            Personnes = new HashSet<Personne>();
        }

        public int id { get; set; }
        public string appartement { get; set; }
        public string rue { get; set; }
        public string ville { get; set; }
        public string zipCode { get; set; }
        public string pays { get; set; }

        public virtual ICollection<Personne> Personnes { get; set; }
    }
}