// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BData.Models
{
    public partial class Domaine
    {
        public Domaine()
        {
            Livres = new HashSet<Livre>();
        }

        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }

        public virtual ICollection<Livre> Livres { get; set; }
    }
}