// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BData.Models
{
    public partial class Livre
    {
        public Livre()
        {
            Emprunters = new HashSet<Emprunter>();
        }

        public int id { get; set; }
        public string tittre { get; set; }
        public int? nbPage { get; set; }
        public int? idDomaine { get; set; }
        public int? idPersonne { get; set; }

        public virtual Domaine idDomaineNavigation { get; set; }
        public virtual Personne idPersonneNavigation { get; set; }
        public virtual ICollection<Emprunter> Emprunters { get; set; }
    }
}