// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BData.Models
{
    public partial class Personne
    {
        public Personne()
        {
            Emprunters = new HashSet<Emprunter>();
            Livres = new HashSet<Livre>();
        }

        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string motDePasse { get; set; }
        public string grade { get; set; }
        public int? idRole { get; set; }
        public int? idAdresse { get; set; }

        public virtual Adresse idAdresseNavigation { get; set; }
        public virtual Role idRoleNavigation { get; set; }
        public virtual ICollection<Emprunter> Emprunters { get; set; }
        public virtual ICollection<Livre> Livres { get; set; }
    }
}